version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: maiinsight-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: maiinsight_db
      MYSQL_USER: maiinsight_app
      MYSQL_PASSWORD: Maiinsight_26
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

volumes:
  mysql_data:
